### ISSUE TITLE
Should lookup Slack users by @mention

### ISSUE THREAD

**Issue by zacstewart** [dirk/lita-markov#1]
Current behavior:

> Me: @lita: markov @zacstewart
> Lita: Couldn't find the user @zacstewart. :(

Expected behvaior:

> Me: @lita: markov @zacstewart
> Lita: Something @zacstewart would say

**Comment by dirk** [comment]
@zacstewart: Nice catch! I'll get this fixed today.

**Comment by dirk** [comment]
@zacstewart: Fixed with 4740973131dff1cb1583fc3cdb7444b1bace175e. Going to cut a new version of the gem now.
